services:
  # -------------- Service Auth -------------- #
  auth-app:
    build: ./services/svc-auth
    container_name: auth-app
    env_file: ./services/svc-auth/.env
    volumes:
      - ./services/svc-auth:/var/www/html # mount source code vào container
    depends_on:
      - auth-db
      - auth-redis

  auth-nginx:
    image: nginx:stable # dùng image Nginx stable
    container_name: auth-nginx
    volumes:
      - ./services/svc-auth:/var/www/html # mount source code vào Nginx
        # mount file config nginx (default.conf) vào thư mục config của Nginx
      - ./services/svc-auth/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8001:80" # map cổng host 8001 -> container port 80
    depends_on:
      - auth-app # đợi PHP-FPM khởi động trước

  auth-db:
    image: mysql:8
    container_name: auth-db
    environment:
      MYSQL_DATABASE: auth_db
      MYSQL_USER: auth
      MYSQL_PASSWORD: auth
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "33061:3306" # map ra cổng 33061 để tránh đụng Laragon MySQL (3306)
    volumes:
      - auth-dbdata:/var/lib/mysql # lưu trữ data ra volume để không mất khi container stop

  auth-redis:
    image: redis:7
    container_name: auth-redis
    ports:
      - "6381:6379" # map ra cổng 6381 để tránh đụng Laragon Redis (6379)

# Volume để giữ dữ liệu MySQL
volumes:
  auth-dbdata:
