services:
  # -------------- Service Auth -------------- #
  auth-app:
    build: ./services/svc-auth
    container_name: auth-app
    env_file: ./services/svc-auth/.env
    volumes:
      - ./services/svc-auth:/var/www/html:rw
      # tách các thư mục nặng sang named volumes (Linux FS) -> nhanh hơn nhiều
      - vendor:/var/www/html/vendor
      - storage:/var/www/html/storage
      - cache:/var/www/html/bootstrap/cache
    depends_on:
      - auth-db
      - auth-redis

  auth-nginx:
    image: nginx:stable
    container_name: auth-nginx
    volumes:
      - ./services/svc-auth:/var/www/html:ro
      - ./services/svc-auth/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8001:80"
    depends_on:
      - auth-app

  auth-db:
    image: mysql:8
    container_name: auth-db
    environment:
      MYSQL_DATABASE: auth_db
      MYSQL_USER: auth
      MYSQL_PASSWORD: auth
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "33061:3306"
    volumes:
      - auth-dbdata:/var/lib/mysql

  auth-redis:
    image: redis:7
    container_name: auth-redis
    ports:
      - "6381:6379"

# Volume để giữ dữ liệu MySQL
volumes:
  auth-dbdata:
  vendor:
  storage:
  cache:
