server {
    listen 80;
    server_name _;

    root /var/www/html/public;
    index index.php index.html;

    # Gzip
    gzip on;
    gzip_types text/plain application/json application/javascript text/css application/xml image/svg+xml;
    gzip_min_length 1024;

    location ~ /\.(env|git|ht|svn) {
        deny all;
    }

    location ^~ /docs/asset/ {
        try_files $uri /index.php?$is_args$args;
        add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0";
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Static (vẫn fallback về PHP để l5-swagger hoạt động)
    location ~* \.(?:css|js|jpg|jpeg|png|gif|ico|svg|webp)$ {
        expires 7d;
        add_header Cache-Control "public, must-revalidate, proxy-revalidate";
        try_files $uri $uri/ /index.php?$is_args$args;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass auth-app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

        fastcgi_read_timeout 120s;
        fastcgi_buffering on;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        fastcgi_param PATH_INFO "";
    }

}
